# Generated by Django 4.2.7 on 2024-02-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blacklistedverificationtoken_verificationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistedverificationtoken',
            old_name='token',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='verificationtoken',
            old_name='token',
            new_name='key',
        ),
    ]
