# Generated by Django 4.2.7 on 2024-02-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_token_blacklistedverificationtoken_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListedVerificationToken',
        ),
    ]
