# Generated by Django 4.2.7 on 2024-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_blacklistedverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
