# Generated by Django 4.2.7 on 2024-02-21 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationtoken_is_blacklisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
